package model.restController;



import model.Entity.Attraction;
import model.service.attractions.AttractionsService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;
@RestController // This means that this class is a Controller
@RequestMapping(path="/attraction")
public class AttractionController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AttractionsService attractionsService;

    @RequestMapping("/all")
    public List<Attraction> findAll(){
        return attractionsService.findAll();
    }


    @RequestMapping("/add")
    public Attraction addUser(@RequestBody Attraction airports) {


        return attractionsService.save( airports );
    }
    @RequestMapping("/{id}")
    public Attraction findOne(@PathVariable Long id){
        return attractionsService.findOne(id);
    }


}
