package model.restController;

import model.Entity.Hotels;

import model.service.hotels.HotelService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

@RestController // This means that this class is a Controller
@RequestMapping(path="/hotels")
public class HotelsController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private HotelService hotelsService;

    @RequestMapping("/all")
    public List<Hotels> findAll(){
        return hotelsService.findAll();
    }


    @RequestMapping("/add")
    public Hotels addUser(@RequestBody Hotels Hotels) {


        return hotelsService.save( Hotels );
    }
    @RequestMapping("/{id}")
    public Hotels findOne(@PathVariable Long id){
        return hotelsService.findOne(id);
    }

}
